// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TaskUsageSummaryEvent = { turnId: string, model: string, totalTokens: bigint, inputTokens: bigint, cachedInputTokens: bigint, outputTokens: bigint, reasoningOutputTokens: bigint, weeklyLimitUsedPercent: number | null, calculatedWeeklyRemainingPercent: number | null, planRemainingPercent: number | null, filesChanged: bigint, filesCreated: bigint, filesDeleted: bigint, filesModified: bigint, linesAdded: bigint, linesRemoved: bigint, wallTimeMs: bigint | null, modelTimeMs: bigint | null, localToolTimeMs: bigint | null, overheadTimeMs: bigint | null, firstOutputMs: bigint | null, finishedAt: bigint | null, };
